// bugs
const emailList = [
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello, some long subject that is too long to fit in the box",
    body: "Hello World, from another world, I am your father, Luke Skywalker",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "John Doe",
    subject: "Hello",
    body: "Hello World, from another world, I am your father, Luke Skywalker",
    dateOrTime: "10:00 AM",
  },
  {
    checked: true,
    sender: "Jane Doe",
    subject: "Hello",
    body: "Hello World",
    dateOrTime: "10:00 AM",
  },
];

export default emailList;
